name: CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

 
jobs:
  build-and-test:
    runs-on: windows-latest
    timeout-minutes: 120
 
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 

 
      # 2️⃣ Setup Node.js 16.3.0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.3.0'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
 

      
 
      
 
     
 
      # 3️⃣ Install npm dependencies
      - name: Install npm dependencies
        shell: pwsh
        run: npm ci --prefer-offline
 
      
 
      
      # 4️⃣ Run GT UI Tests
      - name: Run GT UI Tests
        shell: pwsh
        working-directory: ${{ github.workspace }}
        env:
          SKIP_API_BUILD: true
          GT_SKIP_GRADLE: true
          CC_URL: https://cc-dev-gwcpdev.valuemom.zeta1-andromeda.guidewire.net/ClaimCenter.do
          USERNAME: su
          PASSWORD: gw
        run: npm run gt-ui-tests -- --cucumberTags=@add_activity --pageRequestTimeout=60000 --retryTestPages